FROM python:3.9-slim


RUN apt-get update
RUN apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev gcc mono-mcs ffmpeg libsm6 libxext6 -y && \
    rm -rf /var/lib/apt/lists/*
RUN pip install pyaudio

WORKDIR /app

COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "main_page.py"]